// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMyaamLcJDONnRX9kExYJ_aFnccxbEopo',
    appId: '1:647276787497:web:bd049242cd6be802162938',
    messagingSenderId: '647276787497',
    projectId: 'chat-app-5aa94',
    authDomain: 'chat-app-5aa94.firebaseapp.com',
    storageBucket: 'chat-app-5aa94.appspot.com',
    measurementId: 'G-8LH6XV7X7J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4BRAsQ6d-0dwDv9WmTwzFjoGaDDfyuIM',
    appId: '1:647276787497:android:17e6e247ddf28a84162938',
    messagingSenderId: '647276787497',
    projectId: 'chat-app-5aa94',
    storageBucket: 'chat-app-5aa94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD88nAPcO1yLuLf055dVjSLRPMVfgnJWQs',
    appId: '1:647276787497:ios:798fd99355c15e9c162938',
    messagingSenderId: '647276787497',
    projectId: 'chat-app-5aa94',
    storageBucket: 'chat-app-5aa94.appspot.com',
    iosClientId: '647276787497-ssrujo1siburemumredchm47t63lv1tt.apps.googleusercontent.com',
    iosBundleId: 'com.aldev.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD88nAPcO1yLuLf055dVjSLRPMVfgnJWQs',
    appId: '1:647276787497:ios:164b9d6e47e16581162938',
    messagingSenderId: '647276787497',
    projectId: 'chat-app-5aa94',
    storageBucket: 'chat-app-5aa94.appspot.com',
    iosClientId: '647276787497-5pp5m2fa989lgshj08p40bei44d1q1k0.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
